export const PREVIEW_LINES = 6;
export const SOURCE_VALUES = ["zenmoney"] as const;
export const REGISTER_COLUMNS = [
	"id",
	"period",
	"date",
	"account_id",
	"account_title",
	"account_company",
	"currency",
	"amount",
	"direction",
	"counterparty",
	"description",
	"transaction_type",
	"reference",
	"source",
	"source_file",
	"category_id",
	"category_name",
	"cashflow_bucket",
	"cashflow_category",
	"review_status",
	"classification_source",
	"linked_transfer_id",
	"evidence_file",
	"notes",
] as const;
export const REGISTER_PRESERVED_FIELDS = [
	"cashflow_bucket",
	"cashflow_category",
	"review_status",
	"classification_source",
	"linked_transfer_id",
	"evidence_file",
	"notes",
] as const;
